### ISSUE TITLE
Large file - exception out of memory

### ISSUE THREAD

**Issue by MiddleSiggy** [dionach/NtdsAudit#14]
Having issues with a 6GB ntds.dit file... This is your debug output.

Called: NtdsAudit::EnumerateMSysObjects
  Found 3342 datatable column names
  Completed in 00:00:00.2312898
Called: NtdsAudit::EnumerateLinkTable
  Ignored 54972 deleted backlinks
  Found 1377099 backlinks
  Completed in 00:00:03.0407978
Called: NtdsAudit::EnumerateDatatableTableLdapDisplayNames
  Failed to match 2464 LDAP display names to datatable column names
  Matched 1295 LDAP display names to datatable column names
  Completed in 00:00:07.2350478
Called: NtdsAudit::EnumerateDatatableTable
  Skipped 85197 deleted objects
  Enumerated 612378 objects
  Completed in 00:00:34.9476480
Called: NtdsAudit::DecryptSecretData
Failed to decrypt supplemental credentials for 'user1' with error: Exception of type 'System.OutOfMemoryException' was thrown.
Failed to decrypt supplemental credentials for 'user2' with error: Exception of type 'System.OutOfMemoryException' was thrown.

Let me know how I can help.. I tried to open the project in VS but am having issues getting everything to link up correctly so I can't compile.. I can further debug there if you can assist with all the dependencies around VS.

Thanks

**Comment by CritasPaine** [comment]
Run same file on a machine with only 4GB of RAM.  There may be an issue with addressing larger memory spaces. Ran against a much larger DIT and it worked only on a machine with 2 CPUs and 4GB of RAM.
